title: ExaFEL Project
email: loriordan@lbl.gov
description: ExaFEL Research Project, 2017

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:
github_username:

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-sitemap
exclude:
include: [_pages]
