title: ExaFEL Project
email: loriordan@lbl.gov
description: ExaFEL Research Project, 2017

baseurl: "/docs" # the subpath of your site, e.g. /blog
url: "https://exafel.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:
github_username:

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-sitemap
exclude:
include: [_pages]


defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: "projects"
      type: "pages" # previously `page` in Jekyll 2.2.
    values:
      layout: "project" # overrides previous default layout
      author: "Lee J. O'Riordan"
